[prune]
  go-tests = true

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1"

[[constraint]]
  name = "github.com/mitchellh/go-ps"
  branch = "master"

#[[constraint]]
#  name = "github.com/fsnotify/fsnotify"
#  version = "1"

[[constraint]]
  name = "github.com/pinpt/go-common"
  version = "9"

[[constraint]]  
  name = "github.com/kardianos/service"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1"

[[constraint]]
  name = "github.com/pinpt/integration-sdk"
  version = "0"
  #branch = "TIGR-37"

[[constraint]]
  name = "github.com/denisbrodbeck/machineid"
  version = "0.8.0"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/songgao/stacktraces"

[[override]]
  name = "gopkg.in/src-d/go-git.v4"
  revision = "1a7db85bca7027d90afdb5ce711622aaac9feaed"

#[[constraint]]
#  name = "github.com/pinpt/ripsrc"
#  branch = "slim"
#  revision = "33ce1d7bf6e818a220d58991a3b586b294084907"

# dependency of ripsrc

#[[override]]
#  name = "gopkg.in/src-d/go-license-detector.v2"
#  version = "=2.0.0"

# dependencies of ripsrc, go-license-detector

#[[override]]
#  name = "gopkg.in/src-d/go-git.v4"
#  version = "=4.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/pbnjay/memory"

# dev dependency
# used for uploading releases
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.21"
